# Generated by Django 6.0 on 2026-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="enrollment_date",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course_name",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="course_price",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="courses",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_method",
            field=models.CharField(default="Online", max_length=50),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student_email",
            field=models.EmailField(default="no-email@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
