# Generated by Django 6.0 on 2026-01-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_rename_enrollment_date_enrollment_timestamp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="student_email",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="payment_method",
            field=models.CharField(default="bkash", max_length=50),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student_name",
            field=models.CharField(max_length=255),
        ),
    ]
