# Generated by Django 6.0 on 2026-01-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_enrollment_student_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="student",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
